// Turn an assembled patch ({ raw, vars, labels }) into generated source.

/**
 * Module specifier the generated patches `require` to get the shared linker.
 *
 * It is not a real file: the plugin recognises this exact string in
 * `moduleResolution` and serves `emitLinkLua()` for it, so the runtime is
 * emitted once and shared by every patch instead of being inlined into each.
 */
export const LINK_MODULE = '@noita-ts/nasm/link';

function hexByte(b) {
  return '0x' + b.toString(16).padStart(2, '0');
}

function luaKey(name) {
  return /^[A-Za-z_]\w*$/.test(name) ? name : `[${JSON.stringify(name)}]`;
}

/**
 * The shared patch linker, emitted once per project as its own Lua module and
 * required by every generated patch.
 *
 * Takes a patch table and the reloc values, and returns a fresh copy of `raw`
 * with each reloc's 32-bit value written little-endian at every offset recorded
 * for it in `vars`. `raw` is never mutated, so a patch can be linked repeatedly
 * with different values. Every reloc must be given a value.
 *
 * The module returns a *table* (`{ link = ..., default = ... }`) rather than the
 * bare function on purpose: loaders that wrap module results (such as Noita's
 * `require` shim, which turns a non-table result into `{ default = result }`)
 * would otherwise hand back a table where a function is expected, and using it
 * as a `__call` metamethod fails with "attempt to call a table value".
 */
export function emitLinkLua(banner = 'AUTO-GENERATED by @noita-ts/nasm. Do not edit.') {
  return `-- ${banner}
local band, rshift = bit.band, bit.rshift

--- Links a patch: a copy of \`patch.raw\` with each reloc's value written
--- little-endian at every offset recorded for it in \`patch.vars\`.
--- @param patch table
--- @param values table<string, number>?
--- @return number[]
local function link(patch, values)
  local raw = patch.raw
  local bytes = {}
  for i = 1, #raw do
    bytes[i] = raw[i]
  end
  for name, offsets in pairs(patch.vars) do
    local value = values and values[name]
    if value == nil then
      error(string.format("asm: no value given for reloc '%s'", name), 2)
    end
    for i = 1, #offsets do
      local off = offsets[i]
      bytes[off + 1] = band(value, 0xFF)
      bytes[off + 2] = band(rshift(value, 8), 0xFF)
      bytes[off + 3] = band(rshift(value, 16), 0xFF)
      bytes[off + 4] = band(rshift(value, 24), 0xFF)
    end
  end
  return bytes
end

return { link = link }
`;
}

/**
 * A Lua module (`return { raw, vars, labels }`) for the assembled patch.
 *
 * The table is callable: `patch { name = value }` links it via the shared
 * `asm_link` runtime, returning a fresh copy of `raw` with the reloc values
 * written in. Every reloc must be given a value.
 *
 * The table also points `default` at itself, since the ambient `.asm` types
 * declare a default export and TSTL compiles `import patch from './x.asm'`
 * into a `.default` lookup on the required module.
 */
export function emitLua({ asm, vars, labels }, banner = 'AUTO-GENERATED. Do not edit.') {
  const rows = [];
  for (let i = 0; i < asm.length; i += 12) {
    rows.push('    ' + asm.slice(i, i + 12).map(hexByte).join(', ') + ',');
  }
  const varLines = Object.entries(vars).map(
    ([name, offs]) => `    ${luaKey(name)} = { ${offs.join(', ')} },`,
  );
  const labelLines = Object.entries(labels).map(
    ([name, off]) => `    ${luaKey(name)} = ${off},`,
  );
  return `-- ${banner}
local link = require('${LINK_MODULE}').link

local patch = {
  raw = {
${rows.join('\n')}
  },
  vars = {
${varLines.join('\n')}
  },
  labels = {
${labelLines.join('\n')}
  },
}
patch.default = patch

return setmetatable(patch, { __call = link })
`;
}

const tsKey = (name) => (/^[A-Za-z_]\w*$/.test(name) ? name : JSON.stringify(name));

/** `{ a: T; b: T }` for the given members, or `{}` when there are none. */
const tsObject = (members) => (members.length > 0 ? `{ ${members.join('; ')} }` : '{}');

/** The `{ raw, vars, labels }` type body, concrete when `patch` is given. */
function typeBody(patch) {
  const names = patch && Object.keys(patch.vars);
  const vars = patch
    ? tsObject(names.map((n) => `${tsKey(n)}: number[]`))
    : 'Record<string, number[]>';
  const labels = patch
    ? tsObject(Object.keys(patch.labels).map((n) => `${tsKey(n)}: number`))
    : 'Record<string, number>';
  // With no relocs the argument is pointless, so make it optional; otherwise
  // every reloc must be given a value.
  const values = patch
    ? tsObject(names.map((n) => `${tsKey(n)}: number`))
    : 'Record<string, number>';
  const arg = patch && names.length === 0 ? `values?: ${values}` : `values: ${values}`;  return (
    `{\n` +
    `    /** Raw x86 patch machine code; reloc fields are zeroed. */\n` +
    `    readonly raw: number[];\n` +
    `    /** Byte offsets of each reloc's 32-bit field within \`raw\`. */\n` +
    `    readonly vars: ${vars};\n` +
    `    /** Byte offset of each label within \`raw\`. */\n` +
    `    readonly labels: ${labels};\n` +
    `    /**\n` +
    `     * Links the patch: a copy of \`raw\` with each reloc's value written\n` +
    `     * little-endian at every offset recorded for it in \`vars\`.\n` +
    `     */\n` +
    `    (this: void, ${arg}): number[];\n` +
    `  }`
  );
}

/**
 * An ambient `declare module '<pattern>'` block. Concrete (precise `vars`/`labels`
 * keys) when `patch` is given, otherwise the loose generic fallback.
 */
export function asmModuleBlock(pattern, patch) {
  return (
    `declare module ${JSON.stringify(pattern)} {\n` +
    `  const patch: ${typeBody(patch)};\n` +
    `  export default patch;\n` +
    `}`
  );
}

/** The wildcard ambient-module pattern matching a relative `.asm` specifier. */
export function patternFor(specifier) {
  // Strip leading ./ and ../ so the `*` absorbs the relative prefix.
  return '*/' + specifier.replace(/^(?:\.\.?\/)+/, '');
}

/**
 * The `.d.ts` shipped as `@noita-ts/nasm/asm`: every known patch as a concrete
 * block FIRST (so it wins the wildcard tie against the fallback), then the
 * generic `*.asm` fallback LAST for not-yet-built imports.
 *
 * `modules` is an iterable of `[pattern, patch]`.
 */
export function emitTypesIndex(modules) {
  const blocks = [...modules].map(([pattern, patch]) => asmModuleBlock(pattern, patch));
  blocks.push(asmModuleBlock('*.asm', undefined));
  return (
    `// AUTO-GENERATED by @noita-ts/nasm asm-plugin. Do not edit.\n` +
    `// Concrete per-file blocks come first so they win the wildcard match;\n` +
    `// the generic \`*.asm\` fallback is last for not-yet-built imports.\n\n` +
    blocks.join('\n\n') +
    '\n'
  );
}
