// Turn an assembled patch ({ raw, vars, labels }) into generated source.

/**
 * Module specifier the emitted patches `require` to get the shared linker.
 *
 * It is not a real file: the plugin recognises this exact string in
 * `moduleResolution` and serves `emitLinkLua()` for it, so the runtime is
 * emitted once and shared by every patch instead of being inlined into each.
 */
export const LINK_MODULE = '@noita-ts/nasm/link';

/**
 * The shared patch linker, emitted once per project as its own Lua module and
 * required by every inline patch.
 *
 * Takes a patch table and the reloc values, and returns a fresh copy of `raw`
 * with each reloc's 32-bit value added little-endian into every offset recorded
 * for it in `vars`. Plain reloc fields are zeroed in `raw`, so adding is just a
 * write; `BASE` fields hold the referenced label's offset as an addend, so they
 * become `BASE + offset`. `raw` is never mutated, so a patch can be linked
 * repeatedly with different values. Every reloc must be given a value, except
 * `BASE`: leaving it out yields a function taking the runtime base address and
 * returning the linked bytes (which is what `ffi.cave` feeds the cave address).
 *
 * The module returns a *table* (`{ link = ..., default = ... }`) rather than the
 * bare function on purpose: loaders that wrap module results (such as Noita's
 * `require` shim, which turns a non-table result into `{ default = result }`)
 * would otherwise hand back a table where a function is expected, and using it
 * as a `__call` metamethod fails with "attempt to call a table value".
 */
export function emitLinkLua(banner = 'AUTO-GENERATED by @noita-ts/nasm. Do not edit.') {
  return `-- ${banner}
local M = {}
local band, rshift = bit.band, bit.rshift

local function add32(bytes, off, value)
  value = value
    + bytes[off + 1]
    + bytes[off + 2] * 0x100
    + bytes[off + 3] * 0x10000
    + bytes[off + 4] * 0x1000000
  bytes[off + 1] = band(value, 0xFF)
  bytes[off + 2] = band(rshift(value, 8), 0xFF)
  bytes[off + 3] = band(rshift(value, 16), 0xFF)
  bytes[off + 4] = band(rshift(value, 24), 0xFF)
end

function M.link(patch, values)
  local vars = patch.vars
  if vars.BASE and not (values and values.BASE) then
    return function(base)
      local withBase = { BASE = base }
      if values then
        for name, value in pairs(values) do
          withBase[name] = value
        end
      end
      return M.link(patch, withBase)
    end
  end
  local raw = patch.raw
  local bytes = { entry = patch.labels.entry or 0 }
  for i = 1, #raw do
    bytes[i] = raw[i]
  end
  for name, offsets in pairs(vars) do
    local value = values and values[name]
    if value == nil then
      error(string.format("asm: no value given for reloc '%s'", name), 2)
    end
    for i = 1, #offsets do
      add32(bytes, offsets[i], value)
    end
  end
  return bytes
end

return M
`;
}

/**
 * The `{ raw, vars, labels }` callable as a Lua AST expression, spliced straight
 * into the file the inline `asm` block was written in — a patch has no module of
 * its own.
 *
 * `lua` is typescript-to-lua's AST factory (passed in so this module never has
 * to import tstl itself), and `tsOriginal` the node the expression came from,
 * carried along for source maps.
 *
 * The linker is not inlined along with it: the emitted
 * `require('@noita-ts/nasm/link')` is picked up by TSTL's require scanner and
 * resolved by the plugin to the single shared `asm_link` module.
 */
export function buildPatchExpression(lua, { asm, vars, labels }, tsOriginal) {
  const str = (value) => lua.createStringLiteral(value, tsOriginal);
  const num = (value) => lua.createNumericLiteral(value, tsOriginal);
  const field = (value, key) =>
    lua.createTableFieldExpression(value, key === undefined ? undefined : str(key), tsOriginal);
  const table = (fields) => lua.createTableExpression(fields, tsOriginal);
  const array = (values) => table(values.map((value) => field(num(value))));

  const patch = table([
    field(array(asm), 'raw'),
    field(
      table(Object.entries(vars).map(([name, offs]) => field(array(offs), name))),
      'vars',
    ),
    field(
      table(Object.entries(labels).map(([name, off]) => field(num(off), name))),
      'labels',
    ),
  ]);
  const link = lua.createTableIndexExpression(
    lua.createCallExpression(
      lua.createIdentifier('require', tsOriginal),
      [str(LINK_MODULE)],
      tsOriginal,
    ),
    str('link'),
    tsOriginal,
  );
  return lua.createCallExpression(
    lua.createIdentifier('setmetatable', tsOriginal),
    [patch, table([field(link, '__call')])],
    tsOriginal,
  );
}
