// AUTO-GENERATED by @noita-ts/ffi asm-plugin. Do not edit.
// Concrete per-file blocks come first so they win the wildcard match;
// the generic `*.asm` fallback is last for not-yet-built imports.

declare module "*.asm" {
  const patch: {
    /** Raw x86 patch machine code; reloc fields are zeroed. */
    readonly asm: number[];
    /** Byte offsets of each reloc's 32-bit field within `asm`. */
    readonly vars: Record<string, number[]>;
    /** Byte offset of each label within `asm`. */
    readonly labels: Record<string, number>;
  };
  export default patch;
}
