import ffi from ".";
import { NativeString, Vec2, VoidVec } from "./cpp";
import c from "./schema";

const ControlsConfigKey = c.declare('ControlsConfigKey', [
  c.field("primary", c.i32),
  c.field("secondary", c.i32),
  c.field("primary_name", NativeString),
  c.field("secondary_name", NativeString),
]);
export type ControlsConfigKey = c.infer<typeof ControlsConfigKey>;

const ControlsConfig = c.declare('ControlsConfig', [
  c.field("key_up", ControlsConfigKey),
  c.field("key_down", ControlsConfigKey),
  c.field("key_left", ControlsConfigKey),
  c.field("key_right", ControlsConfigKey),
  c.field("key_use_wand", ControlsConfigKey),
  c.field("key_spray_flask", ControlsConfigKey),
  c.field("key_throw", ControlsConfigKey),
  c.field("key_kick", ControlsConfigKey),
  c.field("key_inventory", ControlsConfigKey),
  c.field("key_interact", ControlsConfigKey),
  c.field("key_drop_item", ControlsConfigKey),
  c.field("key_drink_potion", ControlsConfigKey),
  c.field("key_item_next", ControlsConfigKey),
  c.field("key_item_prev", ControlsConfigKey),
  c.field("key_item_slot1", ControlsConfigKey),
  c.field("key_item_slot2", ControlsConfigKey),
  c.field("key_item_slot3", ControlsConfigKey),
  c.field("key_item_slot4", ControlsConfigKey),
  c.field("key_item_slot5", ControlsConfigKey),
  c.field("key_item_slot6", ControlsConfigKey),
  c.field("key_item_slot7", ControlsConfigKey),
  c.field("key_item_slot8", ControlsConfigKey),
  c.field("key_item_slot9", ControlsConfigKey),
  c.field("key_item_slot10", ControlsConfigKey),
  c.field("key_takescreenshot", ControlsConfigKey),
  c.field("key_replayedit_open", ControlsConfigKey),
  c.field("aim_stick", ControlsConfigKey),
  c.field("key_ui_confirm", ControlsConfigKey),
  c.field("key_ui_drag", ControlsConfigKey),
  c.field("key_ui_quick_drag", ControlsConfigKey),
  c.field("gamepad_analog_sticks_threshold", c.f32),
  c.field("gamepad_analog_buttons_threshold", c.f32),
]);
export type ControlsConfig = c.infer<typeof ControlsConfig>;

enum FullscreenMode {
  WINDOWED = 0,
  STRETCHED = 1,
  FULL = 2,
}

enum VsyncMode {
  OFF = 0,
  ON = 1,
  ADAPTIVE = 2,
}

export const PoroGraphicsSettings = c.declare('PoroGraphicsSettings', [
  c.field("width", c.i32),
  c.field("height", c.i32),
  c.field("fullscreen", c.i32 as c.Type<FullscreenMode>),
  c.field("caption", NativeString),
  c.field("icon_bmp", NativeString),
  c.field("textures_resize_to_power_of_two", c.bool),
  c.field("textures_fix_alpha_channel", c.bool),
  c.field("vsync", c.i32 as c.Type<VsyncMode>),
  c.field("current_display", c.i32),
  c.field("external_context", c.voidptr),
]);

const WizardAppConfig = c.declare('WizardAppConfig', [
  c.field("vftable", c.voidptr),
  c.field("internal_size_w", c.i32),
  c.field("internal_size_h", c.i32),
  c.field("framerate", c.i32),
  c.field("iphone_is_landscape", c.bool),
  c.field("sounds", c.bool),
  c.field("event_recorder_flush_every_frame", c.bool),
  c.field("record_events", c.bool),
  c.field("do_a_playback", c.bool),
  c.field("playback_file", NativeString),
  c.field("report_fps", c.bool),
  c.field("joysticks_enabled", c.bool),
  c.field("joystick_rumble_intensity", c.f32),
  c.field("graphics_settings", PoroGraphicsSettings),
  c.field("set_random_seed_cb", c.voidptr),
  c.field("has_been_started_before", c.bool),
  c.field("audio_fmod", c.bool),
  c.field("audio_music_volume", c.f32),
  c.field("audio_effects_volume", c.f32),
  c.field("rendering_low_quality", c.bool),
  c.field("rendering_low_resolution", c.bool),
  c.field("rendering_pixel_art_antialiasing", c.bool),
  c.field("rendering_brightness_delta", c.f32),
  c.field("rendering_contrast_delta", c.f32),
  c.field("rendering_gamma_delta", c.f32),
  c.field("rendering_teleport_flash_brightness", c.f32),
  c.field("rendering_cosmetic_particle_count_coeff", c.f32),
  c.field("backbuffer_width", c.i32),
  c.field("backbuffer_height", c.i32),
  c.field("application_rendered_cursor", c.bool),
  c.field("screenshake_intensity", c.f32),
  c.field("ui_inventory_icons_always_clickable", c.bool),
  c.field("ui_allow_shooting_while_inventory_open", c.bool),
  c.field("ui_report_damage", c.bool),
  c.field("ui_show_world_hover_info_next_to_mouse", c.bool),
  c.field("replay_recorder_enabled", c.bool),
  c.field("replay_recorder_max_budget_mb", c.u32),
  c.field("replay_recorder_max_resolution_x", c.u32),
  c.field("replay_recorder_max_resolution_y", c.u32),
  c.field("language", NativeString),
  c.field("check_for_updates", c.bool),
  c.field("last_started_game_version_hash", NativeString),
  c.field("config_format_version", c.u32),
  c.field("is_default_config", c.bool),
  c.field("keyboard_controls", ControlsConfig),
  c.field("gamepad_controls", ControlsConfig),
  c.field("gamepad_mode", c.i32),
  c.field("rendering_filmgrain", c.bool),
  c.field("online_features", c.bool),
  c.field("steam_cloud_size_warning_limit_mb", c.f32),
  c.unknown(1), // huh
  c.field("mouse_capture_inside_window", c.bool),
  c.field("ui_snappy_hover_boxes", c.bool),
  c.field("application_pause_when_unfocused", c.bool),
  c.field("gamepad_analog_flying", c.bool),
  c.field("mods_active", NativeString),
  c.field("mods_active_privileged", NativeString),
  c.field("mods_sandbox_enabled", c.bool),
  c.field("mods_sandbox_warning_done", c.bool),
  c.field("mods_disclaimer_accepted", c.bool),
  c.field("streaming_integration_autoconnect", c.bool),
  c.field("streaming_integration_channel_name", NativeString),
  c.field("streaming_integration_events_per_vote", c.u32),
  c.unknown(4),
  c.field("streaming_integration_time_seconds_voting", c.f32),
  c.field("streaming_integration_time_seconds_between_votings", c.f32),
  c.field("streaming_integration_play_new_vote_sound", c.bool),
  c.field("streaming_integration_viewernames_ghosts", c.bool),
  c.field("streaming_integration_hide_votes_during_voting", c.bool),
  c.field("streaming_integration_ui_pos_left", c.bool),
  c.field("single_threaded_loading", c.bool),
  c.unknown(NativeString),
  c.field("DEBUG_DONT_LOAD_OTHER_CONFIG", c.bool),
]);
export type WizardAppConfig = c.infer<typeof WizardAppConfig>;

const Platform = c.declare('Platform', [
  c.field("vftable", c.voidptr),
  c.field("application", c.voidptr),
  c.field("app_config", c.ptr(WizardAppConfig)),
  c.field("internal_width", c.f32),
  c.field("internal_height", c.f32),
  c.field("input_disabled", c.bool),
  c.field("graphics", c.voidptr),
  c.field("fixed_time_step", c.bool),
  c.field("frame_count", c.i32),
  c.field("frame_rate", c.i32),
  c.field("last_frame_execution_time", c.f64),
  c.field("average_frame_execution_time", c.f64),
  c.field("one_frame_should_last", c.f64),
  c.field("time_elapsed_tracker", c.f64),
  c.field("width", c.i32),
  c.field("height", c.i32),
  c.field("event_recorder", c.voidptr),
  c.field("mouse", c.voidptr),
  c.field("keyboard", c.voidptr),
  c.field("touch", c.voidptr),
  c.field("joysticks", VoidVec),
  c.field("sound_player", c.voidptr),
  c.field("file_system", c.voidptr),
  c.field("running", c.bool),
  c.field("mouse_pos", Vec2),
  c.field("sleeping_mode", c.i32),
  c.field("print_framerate", c.bool),
  c.field("working_dir", NativeString),
  c.field("random_i", c.i32),
  c.field("random_seed", c.i32),
  c.field("joysticks_enabled", c.bool),
]);
export type Platform = c.infer<typeof Platform>;

const PLATFORM = ffi.cast<Platform>("Platform*", ffi.locateStaticGlobal(".?AVPlatformWin@poro@@"));

export namespace PLATFORM { }
export default PLATFORM;
